### ISSUE TITLE
Python 2/3 compat

### ISSUE THREAD

**Issue by bignose-debian** [theinternetftw/xyppy#4]
Since Xyppy is primarily an application, there will be no particular benefit from continuing to support Python 2 beyond the end-of-life deadline for Python 2.

What plans are there to migrate the code base so that this application assumes it's running on Python 3?

**Comment by theinternetftw** [comment]
Well, I still find it useful that it runs on Python 2, so the work would be getting it working on both versions.

It's been on the list, but on the backburner.  Bug reports like this help change that.

**Comment by theinternetftw** [comment]
Python 2/3 is now implemented, at least to the point that this general feature issue can be closed in favor of more specific issues dealing with any P3 non-compliance (or P2 regressions).
